package com.moqserver.studio.export.lang.swift

import com.moqserver.studio.export.ExportCatalog
import com.moqserver.studio.export.ExportLanguage
import com.moqserver.studio.export.ExportOptions
import com.moqserver.studio.export.ExportVariant
import com.moqserver.studio.export.GeneratedFile
import com.moqserver.studio.export.LanguageExporter
import com.moqserver.studio.export.support.ExportComments
import com.moqserver.studio.export.support.ExportNameAllocator
import com.moqserver.studio.export.support.SymbolSanitizer

/**
 * Generates Swift source code with caseless namespace enums for API references.
 *
 * Output shape:
 * ```swift
 * enum MoqAPIs {
 *     enum EndpointName {
 *         static let path = "/api/endpoint"
 *         static let method = "GET"
 *         enum Variant: String, CaseIterable {
 *             case success = "success"
 *             var status: Int { ... }
 *             var isDefault: Bool { ... }
 *             var description: String? { ... }
 *         }
 *     }
 * }
 * ```
 */
internal class SwiftExporter : LanguageExporter {

    override val language: ExportLanguage = ExportLanguage.SWIFT

    override fun generate(catalog: ExportCatalog, options: ExportOptions): GeneratedFile {
        val sb = StringBuilder()
        val endpointNames = ExportNameAllocator.endpointNames(
            endpoints = catalog.endpoints,
            normalize = SymbolSanitizer::toPascalCase,
        )

        sb.appendLine("// Auto-generated by moqserver Studio — do not edit.")
        sb.appendLine("// Project: ${catalog.projectName}")
        sb.appendLine()
        sb.appendLine("import Foundation")
        sb.appendLine()

        sb.appendLine("/**")
        sb.appendLine(" Mock API reference constants generated from project \"${catalog.projectName}\".")
        sb.appendLine(" */")
        sb.appendLine("// swiftlint:disable type_body_length file_length")
        sb.appendLine("enum MoqAPIs {")

        catalog.endpoints.forEachIndexed { index, endpoint ->
            if (index > 0) sb.appendLine()
            appendEndpoint(
                sb = sb,
                endpoint = endpoint,
                endpointName = endpointNames.getValue(endpoint.referenceName),
                options = options,
            )
        }

        sb.appendLine("}")
        sb.appendLine("// swiftlint:enable type_body_length file_length")
        sb.appendLine()

        return GeneratedFile(fileName = "MoqAPIs.swift", content = sb.toString())
    }

    private fun appendEndpoint(
        sb: StringBuilder,
        endpoint: com.moqserver.studio.export.ExportEndpoint,
        endpointName: String,
        options: ExportOptions,
    ) {
        val safeEndpointName = SymbolSanitizer.swiftIdentifier(endpointName)
        val descriptionLines = if (options.includeApiDescriptions) {
            ExportComments.lines(endpoint.description)
        } else {
            emptyList()
        }
        sb.appendLine("    /// URL partial path: ${endpoint.method} ${endpoint.path}")
        descriptionLines.forEach { line ->
            sb.appendLine("    /// $line")
        }
        sb.appendLine("    enum $safeEndpointName {")
        sb.appendLine("        static let path = \"${endpoint.path}\"")
        sb.appendLine("        static let method = \"${endpoint.method}\"")
        sb.appendLine()

        appendVariantEnum(sb, endpoint.variants, options)

        sb.appendLine("    }")
    }

    private fun appendVariantEnum(sb: StringBuilder, variants: List<ExportVariant>, options: ExportOptions) {
        val variantNames = ExportNameAllocator.variantNames(
            variants = variants,
            normalize = SymbolSanitizer::toCamelCase,
            withSuffix = { base, suffix -> "$base$suffix" },
        )
        sb.appendLine("        enum Variant: String, CaseIterable {")

        variants.forEach { variant ->
            val safeCaseName = SymbolSanitizer.swiftIdentifier(variantNames.getValue(variant.referenceName))
            val descriptionLines = if (options.includeVariantDescriptions) {
                ExportComments.lines(variant.description)
            } else {
                emptyList()
            }

            descriptionLines.forEach { line ->
                sb.appendLine("            /// $line")
            }
            sb.appendLine("            case $safeCaseName = \"${variant.referenceName}\"")
        }

        sb.appendLine()
        sb.appendLine("            var status: Int {")
        sb.appendLine("                switch self {")
        variants.forEach { variant ->
            val caseName = SymbolSanitizer.swiftIdentifier(variantNames.getValue(variant.referenceName))
            sb.appendLine("                case .$caseName: return ${variant.status}")
        }
        sb.appendLine("                }")
        sb.appendLine("            }")

        sb.appendLine()
        sb.appendLine("            var isDefault: Bool {")
        sb.appendLine("                switch self {")
        variants.forEach { variant ->
            val caseName = SymbolSanitizer.swiftIdentifier(variantNames.getValue(variant.referenceName))
            sb.appendLine("                case .$caseName: return ${variant.isDefault}")
        }
        sb.appendLine("                }")
        sb.appendLine("            }")

        if (options.includeVariantDescriptions) {
            sb.appendLine()
            sb.appendLine("            var variantDescription: String? {")
            sb.appendLine("                switch self {")
            variants.forEach { variant ->
                val caseName = SymbolSanitizer.swiftIdentifier(variantNames.getValue(variant.referenceName))
                val desc = variant.description
                if (desc != null) {
                    sb.appendLine("                case .$caseName: return \"${escapeSwiftString(desc)}\"")
                } else {
                    sb.appendLine("                case .$caseName: return nil")
                }
            }
            sb.appendLine("                }")
            sb.appendLine("            }")
        }

        sb.appendLine("        }")
    }

    private fun escapeSwiftString(value: String): String {
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\t", "\\t")
    }
}
