package com.moqserver.studio.export.lang.swift

import com.moqserver.studio.export.ExportCatalog
import com.moqserver.studio.export.ExportLanguage
import com.moqserver.studio.export.ExportOptions
import com.moqserver.studio.export.ExportVariant
import com.moqserver.studio.export.GeneratedFile
import com.moqserver.studio.export.LanguageExporter
import com.moqserver.studio.export.support.ExportComments
import com.moqserver.studio.export.support.ExportNameAllocator
import com.moqserver.studio.export.support.SymbolSanitizer

/**
 * Generates Swift source code with caseless namespace enums for API references.
 *
 * Path, HTTP method, status, isDefault, and variant descriptions are emitted as doc comments.
 *
 * Output shape:
 * ```swift
 * enum MoqAPIs {
 *     /// GET /api/endpoint
 *     enum EndpointName {
 *         enum Variant: String, CaseIterable {
 *             /// Status: 200 (Default)
 *             /// Description text
 *             case success = "success"
 *         }
 *     }
 * }
 * ```
 */
internal class SwiftExporter : LanguageExporter {

	override val language: ExportLanguage = ExportLanguage.SWIFT

	override fun generate(catalog: ExportCatalog, options: ExportOptions): GeneratedFile {
		val sb = StringBuilder()
		val endpointNames = ExportNameAllocator.endpointNames(
			endpoints = catalog.endpoints,
			normalize = SymbolSanitizer::toPascalCase,
		)

		sb.appendLine("// Auto-generated by moqserver Studio — do not edit.")
		sb.appendLine("// Project: ${catalog.projectName}")
		sb.appendLine()
		sb.appendLine("import Foundation")
		sb.appendLine()

		sb.appendLine("/**")
		sb.appendLine(" Mock API reference constants generated from project \"${catalog.projectName}\".")
		sb.appendLine(" */")
		sb.appendLine("// swiftlint:disable type_body_length file_length")
		sb.appendLine("enum MoqAPIs {")

		catalog.endpoints.forEachIndexed { index, endpoint ->
			if (index > 0) sb.appendLine()
			appendEndpoint(
				sb = sb,
				endpoint = endpoint,
				endpointName = endpointNames.getValue(endpoint.referenceName),
				options = options,
			)
		}

		sb.appendLine("}")
		sb.appendLine("// swiftlint:enable type_body_length file_length")
		sb.appendLine()

		return GeneratedFile(fileName = "MoqAPIs.swift", content = sb.toString())
	}

	private fun appendEndpoint(
		sb: StringBuilder,
		endpoint: com.moqserver.studio.export.ExportEndpoint,
		endpointName: String,
		options: ExportOptions,
	) {
		val safeEndpointName = SymbolSanitizer.swiftIdentifier(endpointName)
		val descriptionLines = if (options.includeApiDescriptions) {
			ExportComments.lines(endpoint.description)
		} else {
			emptyList()
		}
		sb.appendLine("    /// ${endpoint.method} ${endpoint.path}")
		descriptionLines.forEach { line ->
			sb.appendLine("    /// $line")
		}
		sb.appendLine("    enum $safeEndpointName {")

		appendVariantEnum(sb, endpoint.variants, options)

		sb.appendLine("    }")
	}

	private fun appendVariantEnum(sb: StringBuilder, variants: List<ExportVariant>, options: ExportOptions) {
		val variantNames = ExportNameAllocator.variantNames(
			variants = variants,
			normalize = SymbolSanitizer::toCamelCase,
			withSuffix = { base, suffix -> "$base$suffix" },
		)
		sb.appendLine("        enum Variant: String, CaseIterable {")

		variants.forEach { variant ->
			val safeCaseName = SymbolSanitizer.swiftIdentifier(variantNames.getValue(variant.referenceName))
			val defaultMarker = if (variant.isDefault) " (Default)" else ""
			sb.appendLine("            /// Status: ${variant.status}$defaultMarker")

			if (options.includeVariantDescriptions) {
				ExportComments.lines(variant.description).forEach { line ->
					sb.appendLine("            /// $line")
				}
			}
			sb.appendLine("            case $safeCaseName = \"${variant.referenceName}\"")
		}

		sb.appendLine("        }")
	}
}
