package com.moqserver.studio.export.lang.java

import com.moqserver.studio.export.ExportCatalog
import com.moqserver.studio.export.ExportEndpoint
import com.moqserver.studio.export.ExportLanguage
import com.moqserver.studio.export.ExportOptions
import com.moqserver.studio.export.ExportVariant
import com.moqserver.studio.export.GeneratedFile
import com.moqserver.studio.export.LanguageExporter
import com.moqserver.studio.export.support.ExportComments
import com.moqserver.studio.export.support.ExportNameAllocator
import com.moqserver.studio.export.support.SymbolSanitizer

/**
 * Generates Java source code with nested static classes and enums for API references.
 *
 * Output shape:
 * ```java
 * public final class MoqAPIs {
 *     public static final class EndpointName {
 *         public static final String PATH = "/api/endpoint";
 *         public static final String METHOD = "GET";
 *         public enum Variant {
 *             SUCCESS("success", 200, true, "desc"),
 *             ...;
 *             // fields, constructor, getters
 *         }
 *     }
 * }
 * ```
 */
internal class JavaExporter : LanguageExporter {

    override val language: ExportLanguage = ExportLanguage.JAVA

    override fun generate(catalog: ExportCatalog, options: ExportOptions): GeneratedFile {
        val sb = StringBuilder()
        val endpointNames = ExportNameAllocator.endpointNames(
            endpoints = catalog.endpoints,
            normalize = SymbolSanitizer::toPascalCase,
        )

        sb.appendLine("// Auto-generated by moqserver Studio — do not edit.")
        sb.appendLine("// Project: ${catalog.projectName}")
        sb.appendLine()

        options.javaPackage?.takeIf { it.isNotBlank() }?.let { pkg ->
            sb.appendLine("package $pkg;")
            sb.appendLine()
        }

        sb.appendLine("/**")
        sb.appendLine(" * Mock API reference constants generated from project \"${catalog.projectName}\".")
        sb.appendLine(" */")
        sb.appendLine("@SuppressWarnings(\"unused\")")
        sb.appendLine("public final class MoqAPIs {")
        sb.appendLine()
        sb.appendLine("    private MoqAPIs() { }")

        catalog.endpoints.forEachIndexed { index, endpoint ->
            sb.appendLine()
            appendEndpoint(
                sb = sb,
                endpoint = endpoint,
                className = endpointNames.getValue(endpoint.referenceName),
                options = options,
                isLast = index == catalog.endpoints.size - 1,
            )
        }

        sb.appendLine("}")
        sb.appendLine()

        return GeneratedFile(fileName = "MoqAPIs.java", content = sb.toString())
    }

    @Suppress("UnusedParameter")
    private fun appendEndpoint(
        sb: StringBuilder,
        endpoint: ExportEndpoint,
        className: String,
        options: ExportOptions,
        isLast: Boolean,
    ) {
        val descriptionLines = if (options.includeApiDescriptions) {
            ExportComments.lines(endpoint.description)
        } else {
            emptyList()
        }
        sb.appendLine("    /**")
        sb.appendLine("     * URL partial path: ${endpoint.method} ${endpoint.path}")
        if (descriptionLines.isNotEmpty()) {
            sb.appendLine("     *")
            descriptionLines.forEach { line ->
                sb.appendLine("     * $line")
            }
        }
        sb.appendLine("     */")
        sb.appendLine("    public static final class $className {")
        sb.appendLine()
        sb.appendLine("        public static final String PATH = \"${endpoint.path}\";")
        sb.appendLine("        public static final String METHOD = \"${endpoint.method}\";")
        sb.appendLine()

        appendVariantEnum(sb, endpoint.variants, options)

        sb.appendLine()
        sb.appendLine("        private $className() { }")
        sb.appendLine("    }")
    }

    private fun appendVariantEnum(sb: StringBuilder, variants: List<ExportVariant>, options: ExportOptions) {
        val variantNames = ExportNameAllocator.variantNames(
            variants = variants,
            normalize = SymbolSanitizer::toUpperSnakeCase,
            withSuffix = { base, suffix -> "${base}_$suffix" },
        )
        sb.appendLine("        public enum Variant {")

        variants.forEachIndexed { index, variant ->
            val enumName = variantNames.getValue(variant.referenceName)
            val desc = escapeJavaString(if (options.includeVariantDescriptions) variant.description else null)
            val separator = if (index < variants.size - 1) "," else ";"
            val descriptionLines = if (options.includeVariantDescriptions) {
                ExportComments.lines(variant.description)
            } else {
                emptyList()
            }

            if (descriptionLines.isNotEmpty()) {
                sb.appendLine("            /**")
                descriptionLines.forEach { line ->
                    sb.appendLine("             * $line")
                }
                sb.appendLine("             */")
            }
            sb.appendLine(
                "            $enumName(\"${variant.referenceName}\", ${variant.status}, ${variant.isDefault}, $desc)$separator",
            )
        }

        sb.appendLine()
        sb.appendLine("            private final String referenceName;")
        sb.appendLine("            private final int status;")
        sb.appendLine("            private final boolean isDefault;")
        sb.appendLine("            private final String description;")
        sb.appendLine()
        sb.appendLine("            Variant(String referenceName, int status, boolean isDefault, String description) {")
        sb.appendLine("                this.referenceName = referenceName;")
        sb.appendLine("                this.status = status;")
        sb.appendLine("                this.isDefault = isDefault;")
        sb.appendLine("                this.description = description;")
        sb.appendLine("            }")
        sb.appendLine()
        sb.appendLine("            public String getReferenceName() { return referenceName; }")
        sb.appendLine("            public int getStatus() { return status; }")
        sb.appendLine("            public boolean isDefault() { return isDefault; }")
        sb.appendLine("            public String getDescription() { return description; }")
        sb.appendLine("        }")
    }

    private fun escapeJavaString(value: String?): String {
        if (value == null) return "null"
        val escaped = value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\t", "\\t")
        return "\"$escaped\""
    }
}
