package com.moqserver.studio.export.lang.javascript

import com.moqserver.studio.export.ExportCatalog
import com.moqserver.studio.export.ExportEndpoint
import com.moqserver.studio.export.ExportLanguage
import com.moqserver.studio.export.ExportOptions
import com.moqserver.studio.export.ExportVariant
import com.moqserver.studio.export.GeneratedFile
import com.moqserver.studio.export.LanguageExporter
import com.moqserver.studio.export.support.ExportComments
import com.moqserver.studio.export.support.ExportNameAllocator
import com.moqserver.studio.export.support.SymbolSanitizer

/**
 * Generates JavaScript ES module source code with frozen nested objects for API references.
 *
 * Path, HTTP method, status, isDefault, and variant descriptions are emitted as JSDoc comments.
 * Only `referenceName` is kept as an object property.
 *
 * Output shape:
 * ```
 * export const MoqAPIs = Object.freeze({
 *     // GET /api/endpoint
 *     EndpointName: Object.freeze({
 *         Variant: Object.freeze({
 *             // Status: 200 (Default). Description text
 *             SUCCESS: Object.freeze({ referenceName: "success" }),
 *         }),
 *     }),
 * });
 * ```
 */
internal class JavaScriptExporter : LanguageExporter {

	override val language: ExportLanguage = ExportLanguage.JAVASCRIPT

	override fun generate(catalog: ExportCatalog, options: ExportOptions): GeneratedFile {
		val sb = StringBuilder()
		val endpointNames = ExportNameAllocator.endpointNames(
			endpoints = catalog.endpoints,
			normalize = SymbolSanitizer::toPascalCase,
		)

		sb.appendLine("// Auto-generated by moqserver Studio — do not edit.")
		sb.appendLine("// Project: ${catalog.projectName}")
		sb.appendLine()

		sb.appendLine("/**")
		sb.appendLine(" * Mock API reference constants generated from project \"${catalog.projectName}\".")
		sb.appendLine(" */")
		sb.appendLine("export const MoqAPIs = Object.freeze({")

		catalog.endpoints.forEachIndexed { index, endpoint ->
			if (index > 0) sb.appendLine()
			appendEndpoint(
				sb = sb,
				endpoint = endpoint,
				propName = endpointNames.getValue(endpoint.referenceName),
				options = options,
			)
		}

		sb.appendLine("});")
		sb.appendLine()

		return GeneratedFile(fileName = "moq-apis.js", content = sb.toString())
	}

	private fun appendEndpoint(
		sb: StringBuilder,
		endpoint: ExportEndpoint,
		propName: String,
		options: ExportOptions,
	) {
		val descriptionLines = if (options.includeApiDescriptions) {
			ExportComments.lines(endpoint.description)
		} else {
			emptyList()
		}
		sb.appendLine("    /**")
		sb.appendLine("     * ${endpoint.method} ${endpoint.path}")
		if (descriptionLines.isNotEmpty()) {
			sb.appendLine("     *")
			descriptionLines.forEach { line ->
				sb.appendLine("     * $line")
			}
		}
		sb.appendLine("     */")
		sb.appendLine("    $propName: Object.freeze({")

		appendVariants(sb, endpoint.variants, options)

		sb.appendLine("    }),")
	}

	private fun appendVariants(sb: StringBuilder, variants: List<ExportVariant>, options: ExportOptions) {
		val variantNames = ExportNameAllocator.variantNames(
			variants = variants,
			normalize = SymbolSanitizer::toUpperSnakeCase,
			withSuffix = { base, suffix -> "${base}_$suffix" },
		)
		sb.appendLine("        Variant: Object.freeze({")

		variants.forEach { variant ->
			val propName = variantNames.getValue(variant.referenceName)
			val defaultMarker = if (variant.isDefault) " (Default)" else ""
			val descriptionLines = if (options.includeVariantDescriptions) {
				ExportComments.lines(variant.description)
			} else {
				emptyList()
			}

			sb.appendLine("            /**")
			sb.appendLine("             * Status: ${variant.status}$defaultMarker")
			descriptionLines.forEach { line ->
				sb.appendLine("             * $line")
			}
			sb.appendLine("             */")
			sb.appendLine(
				"            $propName: Object.freeze({ " +
					"referenceName: \"${variant.referenceName}\" " +
					"}),",
			)
		}

		sb.appendLine("        }),")
	}
}
