package com.moqserver.studio.export.lang.javascript

import com.moqserver.studio.export.ExportCatalog
import com.moqserver.studio.export.ExportEndpoint
import com.moqserver.studio.export.ExportLanguage
import com.moqserver.studio.export.ExportOptions
import com.moqserver.studio.export.ExportVariant
import com.moqserver.studio.export.GeneratedFile
import com.moqserver.studio.export.LanguageExporter
import com.moqserver.studio.export.support.ExportComments
import com.moqserver.studio.export.support.ExportNameAllocator
import com.moqserver.studio.export.support.SymbolSanitizer

/**
 * Generates JavaScript ES module source code with frozen nested objects for API references.
 *
 * Output shape:
 * ```javascript
 * export const MoqAPIs = Object.freeze({
 *     EndpointName: Object.freeze({
 *         PATH: "/api/endpoint",
 *         METHOD: "GET",
 *         Variant: Object.freeze({
 *             SUCCESS: Object.freeze({ referenceName: "success", status: 200, isDefault: true, description: "desc" }),
 *         }),
 *     }),
 * });
 * ```
 */
internal class JavaScriptExporter : LanguageExporter {

    override val language: ExportLanguage = ExportLanguage.JAVASCRIPT

    override fun generate(catalog: ExportCatalog, options: ExportOptions): GeneratedFile {
        val sb = StringBuilder()
        val endpointNames = ExportNameAllocator.endpointNames(
            endpoints = catalog.endpoints,
            normalize = SymbolSanitizer::toPascalCase,
        )

        sb.appendLine("// Auto-generated by moqserver Studio — do not edit.")
        sb.appendLine("// Project: ${catalog.projectName}")
        sb.appendLine()

        sb.appendLine("/**")
        sb.appendLine(" * Mock API reference constants generated from project \"${catalog.projectName}\".")
        sb.appendLine(" */")
        sb.appendLine("export const MoqAPIs = Object.freeze({")

        catalog.endpoints.forEachIndexed { index, endpoint ->
            if (index > 0) sb.appendLine()
            appendEndpoint(
                sb = sb,
                endpoint = endpoint,
                propName = endpointNames.getValue(endpoint.referenceName),
                options = options,
            )
        }

        sb.appendLine("});")
        sb.appendLine()

        return GeneratedFile(fileName = "moq-apis.js", content = sb.toString())
    }

    private fun appendEndpoint(
        sb: StringBuilder,
        endpoint: ExportEndpoint,
        propName: String,
        options: ExportOptions,
    ) {
        val descriptionLines = if (options.includeApiDescriptions) {
            ExportComments.lines(endpoint.description)
        } else {
            emptyList()
        }
        sb.appendLine("    /**")
        sb.appendLine("     * URL partial path: ${endpoint.method} ${endpoint.path}")
        if (descriptionLines.isNotEmpty()) {
            sb.appendLine("     *")
            descriptionLines.forEach { line ->
                sb.appendLine("     * $line")
            }
        }
        sb.appendLine("     */")
        sb.appendLine("    $propName: Object.freeze({")
        sb.appendLine("        PATH: \"${endpoint.path}\",")
        sb.appendLine("        METHOD: \"${endpoint.method}\",")
        sb.appendLine()

        appendVariants(sb, endpoint.variants, options)

        sb.appendLine("    }),")
    }

    private fun appendVariants(sb: StringBuilder, variants: List<ExportVariant>, options: ExportOptions) {
        val variantNames = ExportNameAllocator.variantNames(
            variants = variants,
            normalize = SymbolSanitizer::toUpperSnakeCase,
            withSuffix = { base, suffix -> "${base}_$suffix" },
        )
        sb.appendLine("        Variant: Object.freeze({")

        variants.forEach { variant ->
            val propName = variantNames.getValue(variant.referenceName)
            val desc = escapeJsString(if (options.includeVariantDescriptions) variant.description else null)
            val descriptionLines = if (options.includeVariantDescriptions) {
                ExportComments.lines(variant.description)
            } else {
                emptyList()
            }

            if (descriptionLines.isNotEmpty()) {
                sb.appendLine("            /**")
                descriptionLines.forEach { line ->
                    sb.appendLine("             * $line")
                }
                sb.appendLine("             */")
            }
            sb.appendLine(
                "            $propName: Object.freeze({ " +
                    "referenceName: \"${variant.referenceName}\", " +
                    "status: ${variant.status}, " +
                    "isDefault: ${variant.isDefault}, " +
                    "description: $desc " +
                    "}),",
            )
        }

        sb.appendLine("        }),")
    }

    private fun escapeJsString(value: String?): String {
        if (value == null) return "null"
        val escaped = value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\t", "\\t")
        return "\"$escaped\""
    }
}
