package com.moqserver.studio.export.lang.kotlin

import com.moqserver.studio.export.ExportCatalog
import com.moqserver.studio.export.ExportLanguage
import com.moqserver.studio.export.ExportOptions
import com.moqserver.studio.export.ExportVariant
import com.moqserver.studio.export.GeneratedFile
import com.moqserver.studio.export.LanguageExporter
import com.moqserver.studio.export.support.ExportComments
import com.moqserver.studio.export.support.ExportNameAllocator
import com.moqserver.studio.export.support.SymbolSanitizer

/**
 * Generates Kotlin source code with nested objects and enum classes for API references.
 *
 * Output shape:
 * ```kotlin
 * object MoqAPIs {
 *     object EndpointName {
 *         const val PATH = "/api/endpoint"
 *         const val METHOD = "GET"
 *         enum class Variant(
 *             val referenceName: String,
 *             val status: Int,
 *             val isDefault: Boolean,
 *             val description: String?,
 *         ) {
 *             SUCCESS("success", 200, true, "desc"),
 *             ...
 *         }
 *     }
 * }
 * ```
 */
internal class KotlinExporter : LanguageExporter {

    override val language: ExportLanguage = ExportLanguage.KOTLIN

    override fun generate(catalog: ExportCatalog, options: ExportOptions): GeneratedFile {
        val sb = StringBuilder()
        val endpointNames = ExportNameAllocator.endpointNames(
            endpoints = catalog.endpoints,
            normalize = SymbolSanitizer::toPascalCase,
        )

        sb.appendLine("// Auto-generated by moqserver Studio — do not edit.")
        sb.appendLine("// Project: ${catalog.projectName}")
        sb.appendLine()

        options.kotlinPackage?.takeIf { it.isNotBlank() }?.let { pkg ->
            sb.appendLine("package $pkg")
            sb.appendLine()
        }

        sb.appendLine("/**")
        sb.appendLine(" * Mock API reference constants generated from project \"${catalog.projectName}\".")
        sb.appendLine(" */")
        sb.appendLine("@Suppress(\"unused\")")
        sb.appendLine("object MoqAPIs {")

        catalog.endpoints.forEachIndexed { index, endpoint ->
            if (index > 0) sb.appendLine()
            appendEndpoint(
                sb = sb,
                endpoint = endpoint,
                endpointName = endpointNames.getValue(endpoint.referenceName),
                options = options,
            )
        }

        sb.appendLine("}")
        sb.appendLine()

        return GeneratedFile(fileName = "MoqAPIs.kt", content = sb.toString())
    }

    private fun appendEndpoint(
        sb: StringBuilder,
        endpoint: com.moqserver.studio.export.ExportEndpoint,
        endpointName: String,
        options: ExportOptions,
    ) {
        val descriptionLines = if (options.includeApiDescriptions) {
            ExportComments.lines(endpoint.description)
        } else {
            emptyList()
        }
        sb.appendLine("\t/**")
        sb.appendLine("\t * URL partial path: ${endpoint.method} ${endpoint.path}")
        if (descriptionLines.isNotEmpty()) {
            sb.appendLine("\t *")
            descriptionLines.forEach { line ->
                sb.appendLine("\t * $line")
            }
        }
        sb.appendLine("\t */")
        sb.appendLine("\tobject $endpointName {")
        sb.appendLine("\t\tconst val PATH = \"${endpoint.path}\"")
        sb.appendLine("\t\tconst val METHOD = \"${endpoint.method}\"")
        sb.appendLine()

        appendVariantEnum(sb, endpoint.variants, options)

        sb.appendLine("\t}")
    }

    private fun appendVariantEnum(sb: StringBuilder, variants: List<ExportVariant>, options: ExportOptions) {
        val variantNames = ExportNameAllocator.variantNames(
            variants = variants,
            normalize = SymbolSanitizer::toUpperSnakeCase,
            withSuffix = { base, suffix -> "${base}_$suffix" },
        )
        sb.appendLine("\t\tenum class Variant(")
        sb.appendLine("\t\t\tval referenceName: String,")
        sb.appendLine("\t\t\tval status: Int,")
        sb.appendLine("\t\t\tval isDefault: Boolean,")
        sb.appendLine("\t\t\tval description: String?,")
        sb.appendLine("\t\t) {")

        variants.forEachIndexed { index, variant ->
            val enumName = variantNames.getValue(variant.referenceName)
            val desc = if (options.includeVariantDescriptions) escapeKotlinString(variant.description) else "null"
            val descriptionLines = if (options.includeVariantDescriptions) {
                ExportComments.lines(variant.description)
            } else {
                emptyList()
            }

            if (descriptionLines.isNotEmpty()) {
                sb.appendLine("\t\t\t/**")
                descriptionLines.forEach { line ->
                    sb.appendLine("\t\t\t * $line")
                }
                sb.appendLine("\t\t\t */")
            }

            val separator = if (index < variants.size - 1) "," else ","
            sb.appendLine(
                "\t\t\t$enumName(\"${variant.referenceName}\", ${variant.status}, ${variant.isDefault}, $desc)$separator",
            )
        }

        sb.appendLine("\t\t}")
    }

    private fun escapeKotlinString(value: String?): String {
        if (value == null) return "null"
        val escaped = value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\t", "\\t")
        return "\"$escaped\""
    }
}
