package com.moqserver.studio.export.lang.kotlin

import com.moqserver.studio.export.ExportCatalog
import com.moqserver.studio.export.ExportLanguage
import com.moqserver.studio.export.ExportOptions
import com.moqserver.studio.export.ExportVariant
import com.moqserver.studio.export.GeneratedFile
import com.moqserver.studio.export.LanguageExporter
import com.moqserver.studio.export.support.ExportComments
import com.moqserver.studio.export.support.ExportNameAllocator
import com.moqserver.studio.export.support.SymbolSanitizer

/**
 * Generates Kotlin source code with nested objects and enum classes for API references.
 *
 * Path, HTTP method, status, isDefault, and variant descriptions are emitted as KDoc comments.
 * Only `referenceName` is kept as an enum property.
 *
 * Output shape:
 * ```
 * object MoqAPIs {
 *     // GET /api/endpoint
 *     object EndpointName {
 *         enum class Variant(
 *             val referenceName: String,
 *         ) {
 *             // Status: 200 (Default). Description text
 *             SUCCESS("success"),
 *             ...
 *         }
 *     }
 * }
 * ```
 */
internal class KotlinExporter : LanguageExporter {

	override val language: ExportLanguage = ExportLanguage.KOTLIN

	override fun generate(catalog: ExportCatalog, options: ExportOptions): GeneratedFile {
		val sb = StringBuilder()
		val endpointNames = ExportNameAllocator.endpointNames(
			endpoints = catalog.endpoints,
			normalize = SymbolSanitizer::toPascalCase,
		)

		sb.appendLine("// Auto-generated by moqserver Studio — do not edit.")
		sb.appendLine("// Project: ${catalog.projectName}")
		sb.appendLine()

		options.kotlinPackage?.takeIf { it.isNotBlank() }?.let { pkg ->
			sb.appendLine("package $pkg")
			sb.appendLine()
		}

		sb.appendLine("/**")
		sb.appendLine(" * Mock API reference constants generated from project \"${catalog.projectName}\".")
		sb.appendLine(" */")
		sb.appendLine("@Suppress(\"unused\")")
		sb.appendLine("object MoqAPIs {")

		catalog.endpoints.forEachIndexed { index, endpoint ->
			if (index > 0) sb.appendLine()
			appendEndpoint(
				sb = sb,
				endpoint = endpoint,
				endpointName = endpointNames.getValue(endpoint.referenceName),
				options = options,
			)
		}

		sb.appendLine("}")
		sb.appendLine()

		return GeneratedFile(fileName = "MoqAPIs.kt", content = sb.toString())
	}

	private fun appendEndpoint(
		sb: StringBuilder,
		endpoint: com.moqserver.studio.export.ExportEndpoint,
		endpointName: String,
		options: ExportOptions,
	) {
		val descriptionLines = if (options.includeApiDescriptions) {
			ExportComments.lines(endpoint.description)
		} else {
			emptyList()
		}
		sb.appendLine("\t/**")
		sb.appendLine("\t * ${endpoint.method} ${endpoint.path}")
		if (descriptionLines.isNotEmpty()) {
			sb.appendLine("\t *")
			descriptionLines.forEach { line ->
				sb.appendLine("\t * $line")
			}
		}
		sb.appendLine("\t */")
		sb.appendLine("\tobject $endpointName {")

		appendVariantEnum(sb, endpoint.variants, options)

		sb.appendLine("\t}")
	}

	private fun appendVariantEnum(sb: StringBuilder, variants: List<ExportVariant>, options: ExportOptions) {
		val variantNames = ExportNameAllocator.variantNames(
			variants = variants,
			normalize = SymbolSanitizer::toUpperSnakeCase,
			withSuffix = { base, suffix -> "${base}_$suffix" },
		)
		sb.appendLine("\t\tenum class Variant(")
		sb.appendLine("\t\t\tval referenceName: String,")
		sb.appendLine("\t\t) {")

		variants.forEachIndexed { index, variant ->
			val enumName = variantNames.getValue(variant.referenceName)
			val defaultMarker = if (variant.isDefault) " (Default)" else ""
			val descriptionLines = if (options.includeVariantDescriptions) {
				ExportComments.lines(variant.description)
			} else {
				emptyList()
			}

			sb.appendLine("\t\t\t/**")
			sb.appendLine("\t\t\t * Status: ${variant.status}$defaultMarker")
			descriptionLines.forEach { line ->
				sb.appendLine("\t\t\t * $line")
			}
			sb.appendLine("\t\t\t */")

			val separator = if (index < variants.size - 1) "," else ","
			sb.appendLine(
				"\t\t\t$enumName(\"${variant.referenceName}\")$separator",
			)
		}

		sb.appendLine("\t\t}")
	}
}
